name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      API_HOST: ${{ secrets.API_HOST }}
      API_PORT: ${{ secrets.API_PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker
        run: |
          docker compose build

      - name: Run Tests Backend
        run: |
          docker compose run backend pytest --cache-clear --maxfail=5 --disable-warnings

      - name: Deploy
        run: |
          docker compose down
          docker compose up --build -d
