name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      API_HOST: ${{ secrets.API_HOST }}
      API_PORT: ${{ secrets.API_PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config Docker
        uses: docker/setup-buildx-action@v2

      - name: Config env
        run: |
          echo "MONGO_URI=${MONGO_URI}" >> backend/.env
          echo "API_HOST=${API_HOST}" >> backend/.env
          echo "API_PORT=${API_PORT}" >> backend/.env
          echo "SECRET_KEY=${SECRET_KEY}" >> backend/.env
          echo "ALGORITHM=${ALGORITHM}" >> backend/.env
          echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" >> frontend/.env

      - name: Build Docker
        run: |
          docker compose build

      - name: Run Tests Backend
        run: |
          docker compose run backend pytest --cache-clear --maxfail=5 --disable-warnings

      - name: Deploy
        run: |
          docker compose down
          docker compose up --build -d
